// This is an autogenerated file from Firebase Studio.
"use server";

/**
 * @fileOverview A candidate job matching AI agent.
 *
 * - candidateJobMatch - A function that handles the candidate job matching process.
 * - CandidateJobMatchInput - The input type for the candidateJobMatch function.
 * - CandidateJobMatchOutput - The return type for the candidateJobMatch function.
 */

import { ai } from "@/ai/genkit";
import { z } from "genkit";

const CandidateJobMatchInputSchema = z.object({
  resumeText: z.string().describe("The text content of the resume."),
  jobDescription: z.string().describe("The job description text."),
});
export type CandidateJobMatchInput = z.infer<
  typeof CandidateJobMatchInputSchema
>;

const CandidateJobMatchOutputSchema = z.object({
  matchScore: z
    .number()
    .describe(
      "A score indicating how well the candidate matches the job (0-100)."
    ),
  insights: z
    .string()
    .describe("AI-generated insights about the candidate-job match."),
  missingSkills: z
    .array(z.string())
    .describe("A list of skills missing from the candidate."),
  topSkills: z
    .array(z.string())
    .describe("A list of the candidate top skills."),
});
export type CandidateJobMatchOutput = z.infer<
  typeof CandidateJobMatchOutputSchema
>;

export async function candidateJobMatch(
  input: CandidateJobMatchInput
): Promise<CandidateJobMatchOutput> {
  return candidateJobMatchFlow(input);
}

const prompt = ai.definePrompt({
  name: "candidateJobMatchPrompt",
  input: { schema: CandidateJobMatchInputSchema },
  output: { schema: CandidateJobMatchOutputSchema },
  prompt: `You are an AI-powered HR assistant. Your task is to evaluate how well a candidate's resume matches a given job description and provide a match score, insights, and identify missing skills.

Resume Text: {{{resumeText}}}

Job Description: {{{jobDescription}}}

Based on the resume and job description, provide the following:

1.  **Match Score:** A numerical score (0-100) representing the overall fit of the candidate for the job.
2.  **Insights:** A concise paragraph summarizing the candidate's strengths and weaknesses in relation to the job requirements.
3.  **Missing Skills:** A bulleted list of essential skills mentioned in the job description that are not evident in the resume.
4.  **Top Skills:**  A bulleted list of the candidate's key skills.

Please ensure the output is well-structured and easy to understand for HR professionals.`,
});

const candidateJobMatchFlow = ai.defineFlow(
  {
    name: "candidateJobMatchFlow",
    inputSchema: CandidateJobMatchInputSchema,
    outputSchema: CandidateJobMatchOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
